name: Lint


on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/lint.yml'
      - 'core/**/*.ts'
      - 'core/**/*.tsx'
      - 'core/**/*.css'
      - 'app/**/*.ts'
      - 'app/**/*.tsx'
      - 'app/**/*.css'
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]
    steps:
      - uses: actions/checkout@v3


      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-


      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list


      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'


      - run: npm ci
      - run: npx next lint
      - run: npx tsc
