name: Package


on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/package.yml'
      - 'package.json'
      - 'core/**/*.ts'
      - 'core/**/*.tsx'
      - 'core/**/*.css'
    branches:
      - main
  pull_request:
    branches:
      - main


env:
  node-version: '18'


jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      # setup-node action creates an .npmrc file on the runner
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          registry-url: 'https://npm.pkg.github.com'


      - run: npm ci
      - run: |
          npm version "$(date +%Y).$(date +%j).$(( $(date +%s) % 86400 ))" --no-commit-hooks --no-git-tag-version
      - run: npm pack
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Push a commit using the built-in token
        run: |
          git pull origin main
          git config --local user.name $GITHUB_ACTOR
          git config --local user.email $(git --no-pager show --format="<%ae>" -s HEAD)
          if git status | grep -q "working tree clean"
            echo "No changes since last run"
          then
            git add -- package.json package-lock.json
            git commit -m "$(cat package.json | jq -r '.version') [package.yml] [ci skip]"
            git remote -v
            git push
          fi


      - name: Discord action job digest notification
        uses: sarisia/actions-status-discord@v1
        if: always() # Pick up events even if the job fails or is canceled.
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
